version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: schooldb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/schooldb
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data: